locales:
  ru:
    name: Дмитрий Евдокимов
    tagline: Персональный сайт
    home: Главная
    path: /
  en:
    name: Dmitrii Evdokimov
    tagline: Personal Website
    home: Home Page
    path: /en/

theme: jekyll-theme-midnight
google_analytics: 

defaults:
  - 
    scope:
      path: _docs
      type: docs
    values:
      layout: default

collections:
  docs:
    permalink: /:path/
    output: true

gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - [vendor]
